### ISSUE TITLE
The gem error in rails 5.0

### ISSUE THREAD

**Issue by colorfulberry** [rails-sqlserver/activerecord-sqlserver-adapter#519]
I am in rails 5.0.0.1
when 
`gem 'activerecord-sqlserver-adapter'`

```
There was an error while trying to load the gem 'activerecord-sqlserver-adapter'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `add_order!' for class `#<Class:ActiveRecord::Base>'
```
But  `gem 'activerecord-sqlserver-adapter', git: 'https://github.com/rails-sqlserver/activerecord-sqlserver-adapter'` correct.

I want to know why?

**Comment by DarkSideF** [comment]
This is because the version for rails 5 is unstable and not released yet.
So rubygems contains only stable version.

P.S. 
Gemfile use rubygems.org source by default . 
At the beginning of your Gemfile you can find `source 'rubygems.org'`

**Comment by metaskills** [comment]
Thanks, closing this. I've started major work on getting the master branch w 5.0.x support working. Almost done with re-architecting #504 per Sean G. comments.

**Comment by colorfulberry** [comment]
Thanks.
