### PR TITLE
Added prepared statement caching

### PR DESCRIPTION
**Pull request by aidanharan**
Fix the failing tests that were introduced by https://github.com/rails/rails/pull/35399

### Binding Parameter Tests

`bundle exec rake test TEST_FILES_AR="test/cases/bind_parameter_test.rb"`

### Before

The failing tests had error:
```
NoMethodError: undefined method `cache' for nil:NilClass
```

```
Finished in 3.639557s, 3.5719 runs/s, 4.6709 assertions/s.
13 runs, 17 assertions, 0 failures, 5 errors, 0 skips
```
### After

```
Finished in 3.277385s, 3.9666 runs/s, 8.8485 assertions/s.
13 runs, 29 assertions, 0 failures, 0 errors, 0 skips
```

### CODE REVIEW

**Comment by aidanharan** [comment]
Closed in favor of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/744

This MR tried to pretend we used prepared statements in the SQL Server adapter. However, the adapter doesn't used prepared statements as query plans are already reused by MSSQL when we use `EXEC sp_executesq`.
