### ISSUE TITLE
Rails 8: SQL Server trigger-fired INSERT returns array-wrapped identity ([1]), causing NoMethodError in integer deserialization

### ISSUE THREAD

**Issue by djberg96** [rails-sqlserver/activerecord-sqlserver-adapter#1391]
Howdy folks.

Real person here who had to get some help from AI for this one, hope that's ok since there was no way I would've figured this one out on my own.

The short version is we're trying to upgrade from Rails 7 to Rails 8 and hitting an unusual issue with triggers. Most of the text below was crafted by GPT 5.5 under my guidance:

# Title

Rails 8 + activerecord-sqlserver-adapter 8.0.10: triggered INSERT can return array-wrapped identity ([1]) and fail integer deserialization

## Summary

During a Rails 7 to Rails 8 upgrade, we observed INSERT failures only when an AFTER INSERT trigger fires on SQL Server. In failing cases, the adapter returns an array-wrapped value for the inserted identity, and Rails 8 raises:

NoMethodError: undefined method to_i for an instance of Array

Non-trigger inserts continue to work.

## Environment

- Rails: 8.0.5
- activerecord-sqlserver-adapter: 8.0.10
- Ruby: 3.3.x
- SQL Server: 2022

## Steps To Reproduce

1. Use Rails 8 and activerecord-sqlserver-adapter 8.0.10.
2. Set ActiveRecord::ConnectionAdapters::SQLServerAdapter.use_output_inserted = false.
3. Create a table with identity PK and an AFTER INSERT trigger that performs additional DML.
4. Insert one row where trigger criteria does not match.
5. Insert one row where trigger criteria matches.
6. Instrument adapter methods last_inserted_id and returning_column_values to inspect returned shapes.

## Minimal Trigger Shape (Anonymized)

```sql
CREATE TRIGGER [dbo].[WorkflowTrigger_NEW] ON [dbo].[EventTable]
AFTER INSERT
AS
BEGIN
  INSERT [dbo].[WorkflowAudit]
  (event_id, workflow_state_id, action_id)
  SELECT i.id, wf.state_id, wf.action_id
  FROM inserted i
  LEFT JOIN [dbo].[WorkflowState] r ON r.id = i.state_id
  JOIN [dbo].[WorkflowDefinition] wf ON wf.state_id = r.id
  WHERE wf.criteria IN ('Shared', 'Accessed', 'Archived')
END
```

## Expected Behavior

Both inserts return scalar identity values and succeed, regardless of trigger execution.

## Actual Behavior

When trigger does not fire:

```text
last_inserted_id => 583 (Integer)
returning_column_values => [583] (Array)
OK id=583 (Integer)
```

When trigger fires:

```text
last_inserted_id => [1] (Array)
returning_column_values => [[1]] (Array)
FAIL NoMethodError: undefined method `to_i` for an instance of Array
```

## Additional Confirmed Findings

In our testing environment:

- Session NOCOUNT: OFF
- Server default NOCOUNT: OFF
- Trigger Workflow: NOCOUNT not specified
- Trigger SetRequestOutcome: NOCOUNT not specified

So this is not caused by a session/server NOCOUNT ON configuration.

## Why This Appears As Rails 7 vs Rails 8

The adapter return shape issue existed but was effectively tolerated in earlier behavior. Rails 8 stricter integer coercion now surfaces it immediately when an Array reaches integer deserialization.

## Current Workaround

```ruby
ActiveRecord::ConnectionAdapters::SQLServerAdapter.use_output_inserted = false

module SQLServerAdapterPatch
  def last_inserted_id(result)
    value = super
    value = value.first if value.is_a?(Array) && value.size == 1 && !value.first.is_a?(Array)
    value
  end

  def returning_column_values(result)
    values = super
    values = values.map { |v| v.is_a?(Array) && v.size == 1 ? v.first : v } if values.is_a?(Array)
    values
  end
end

ActiveRecord::ConnectionAdapters::SQLServerAdapter.prepend(SQLServerAdapterPatch)
```

## Proposed Fix

Any of the following should address this class of issue:

1. Ignore trigger-generated intermediate result rows when computing identity return values.
2. Normalize last_inserted_id and returning_column_values so single identity paths never return array-wrapped scalars.
3. Add regression tests for AFTER INSERT triggers that emit extra result shapes when use_output_inserted = false.

## Notes

- exclude_output_inserted_table_names did not resolve this by itself.
- use_output_inserted = false was necessary but not sufficient in this failing path.

Ok, it's me again, the human. If necessary I can checkin a minimal repo with docker, rails, etc to demonstrate the issue.

Or if this is something obvious, I'm all ears!

**Comment by aidanharan** [comment]
@djberg96 Would you be able to create a reproducible script that demonstrates the issue? You can find the template for it at https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/wiki/How-to-report-a-bug

**Comment by djberg96-mckesson** [comment]
@aidanharan I've got a simple setup that should demonstrate it at https://github.com/djberg96-mckesson/SqlServerTest. So:

* git clone git@github.com:djberg96-mckesson/SqlServerTest
* docker compose up -d sqlserver
* bundle install
* bundle exec ruby simple_trigger_repro.rb

**Comment by djberg96-mckesson** [comment]
@aidanharan any thoughts?

**Comment by aidanharan** [comment]
Would you be able to create a reproducible script that demonstrates the issue? You can find the template for it at https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/wiki/How-to-report-a-bug

**Comment by djberg96-mckesson** [comment]
@aidanharan Here's the script from the repo I mentioned earlier.

```ruby
#!/usr/bin/env ruby

# Instructions:
# docker compose up -d sqlserver
# bundle install
# bundle exec ruby simple_trigger_repro.rb
require_relative "config/environment"

class ReproRequest < ActiveRecord::Base
  self.table_name = "T_Requests"
  self.primary_key = "Id"
end

class ReproRequestTouch < ActiveRecord::Base
  self.table_name = "T_RequestTouches"
  self.primary_key = "Id"
end

conn = ActiveRecord::Base.connection
schema_sql = File.read(File.join(__dir__, "db", "schema.sql"))

# Execute the schema script so the trigger exists for this one-off repro.
schema_sql.split(/;\s*\n/).map(&:strip).reject(&:empty?).each do |statement|
  conn.execute(statement)
end

puts "Creating request..."
request = ReproRequest.create!

puts "Creating trigger-causing touch (TouchType=2)..."
# On Rails 8 + activerecord-sqlserver-adapter 8.0.10 this line raises:
# NoMethodError: undefined method `to_i' for an instance of Array
ReproRequestTouch.create!(RequestId: request.id, TouchType: 2)

puts "Unexpected: insert succeeded (issue did not reproduce)."
```

**Comment by DorindaFischer** [comment]
I also encountered this issue when upgrading a Rails app from 7.2 to 8.0. Claude Opus suggested adding the following initializer as a bug fix, but I don't know if this is any better than the previous workaround that was posted.
```
# frozen_string_literal: true

# Works around a bug in activerecord-sqlserver-adapter 8.0.x where INSERTs into a
# table with an AFTER INSERT trigger (e.g. T_RequestTouches) return the trigger's
# own intermediate result set instead of the actual identity value. The adapter's
# `handle_to_names_and_values` already collapses `columns` down to the last result
# set when a statement batch produces more than one, but it forgets to do the same
# for `results`, so the returned rows end up mismatched with the columns and
# `_create_record` raises `NoMethodError: undefined method 'to_i' for an instance
# of Array` when deserializing the identity column.
#
# Upstream issue: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1391
if ActiveRecord::Base.connection_db_config.configuration_hash[:adapter] == 'sqlserver'
  module SQLServerAdapterMultiResultSetFix
    def handle_to_names_and_values(handle, options = {})
      query_options = {}.tap do |qo|
        qo[:timezone] = ActiveRecord.default_timezone || :utc
        qo[:as] = (options[:ar_result] || options[:fetch] == :rows) ? :array : :hash
      end
      results = handle.each(query_options)
      columns = handle.fields

      if columns.any? && columns.all? { |e| e.is_a?(Array) }
        columns = columns.last
        results = results.last
      end
      columns = columns.map(&:downcase) if lowercase_schema_reflection

      options[:ar_result] ? ActiveRecord::Result.new(columns, results) : results
    end
  end

  ActiveRecord::ConnectionAdapters::SQLServerAdapter.prepend(SQLServerAdapterMultiResultSetFix)
end
```

**Comment by aidanharan** [comment]
Could you create PRs with the fixes and include a test that works when your fix is applied?

**Comment by djberg96-mckesson** [comment]
@aidanharan Since I'm not even totally sure that's the proper fix, I think that's a bad idea. I'm afraid I'm going to have to leave this in your capabable hands, as this was an AI generated solution that I cannot validate since I really don't know the internals at all. Anyone stumbling across this issue can adopt either @DorindaFischer's workaround or mine as needed in the meantime.

**Comment by DorindaFischer** [comment]
I agree with @djberg96-mckesson's comment. The workaround I posted was generated with AI and I'm entirely unsure if it's correct or appropriate for all situations, although it did allow my app's rspec tests to pass. In fact, I asked Claude to examine its own changes and improve them if possible and it gave me a new version. Leaving it here for the next person.
```
module SQLServerAdapterMultiResultSetFix
  def handle_to_names_and_values(handle, options = {})
    result = super

    # `fields` is an array-of-arrays only when the batch produced multiple result sets.
    # It stays readable after the handle has been iterated by `super`.
    fields = handle.fields
    return result unless fields.is_a?(Array) && fields.any? && fields.all? { |f| f.is_a?(Array) }

    rows = options[:ar_result] ? result.rows : result
    # Leave the result alone rather than guess if the rows don't correspond one-to-one
    # with the result sets -- a wrong id is worse than the upstream error.
    return result unless rows.is_a?(Array) && rows.size == fields.size

    options[:ar_result] ? ActiveRecord::Result.new(result.columns, rows.last) : rows.last
  end
end

if ActiveRecord::Base.connection_db_config.configuration_hash[:adapter] == 'sqlserver'
  ActiveRecord::ConnectionAdapters::SQLServerAdapter.prepend(SQLServerAdapterMultiResultSetFix)
end
```
